package com.ota.domain;

public class AdvertisementMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.romversion
     *
     * @mbggenerated
     */
    private String romversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.businessid
     *
     * @mbggenerated
     */
    private String businessid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.appversion
     *
     * @mbggenerated
     */
    private String appversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.hardwareversion
     *
     * @mbggenerated
     */
    private String hardwareversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.manufacturer
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.dvbsupport
     *
     * @mbggenerated
     */
    private Boolean dvbsupport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.homeui
     *
     * @mbggenerated
     */
    private String homeui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.ipbegin
     *
     * @mbggenerated
     */
    private String ipbegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisementmapping.ipend
     *
     * @mbggenerated
     */
    private String ipend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.id
     *
     * @return the value of advertisementmapping.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.id
     *
     * @param id the value for advertisementmapping.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.romversion
     *
     * @return the value of advertisementmapping.romversion
     *
     * @mbggenerated
     */
    public String getRomversion() {
        return romversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.romversion
     *
     * @param romversion the value for advertisementmapping.romversion
     *
     * @mbggenerated
     */
    public void setRomversion(String romversion) {
        this.romversion = romversion == null ? null : romversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.type
     *
     * @return the value of advertisementmapping.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.type
     *
     * @param type the value for advertisementmapping.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.userid
     *
     * @return the value of advertisementmapping.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.userid
     *
     * @param userid the value for advertisementmapping.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.businessid
     *
     * @return the value of advertisementmapping.businessid
     *
     * @mbggenerated
     */
    public String getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.businessid
     *
     * @param businessid the value for advertisementmapping.businessid
     *
     * @mbggenerated
     */
    public void setBusinessid(String businessid) {
        this.businessid = businessid == null ? null : businessid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.appversion
     *
     * @return the value of advertisementmapping.appversion
     *
     * @mbggenerated
     */
    public String getAppversion() {
        return appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.appversion
     *
     * @param appversion the value for advertisementmapping.appversion
     *
     * @mbggenerated
     */
    public void setAppversion(String appversion) {
        this.appversion = appversion == null ? null : appversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.hardwareversion
     *
     * @return the value of advertisementmapping.hardwareversion
     *
     * @mbggenerated
     */
    public String getHardwareversion() {
        return hardwareversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.hardwareversion
     *
     * @param hardwareversion the value for advertisementmapping.hardwareversion
     *
     * @mbggenerated
     */
    public void setHardwareversion(String hardwareversion) {
        this.hardwareversion = hardwareversion == null ? null : hardwareversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.manufacturer
     *
     * @return the value of advertisementmapping.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.manufacturer
     *
     * @param manufacturer the value for advertisementmapping.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.dvbsupport
     *
     * @return the value of advertisementmapping.dvbsupport
     *
     * @mbggenerated
     */
    public Boolean getDvbsupport() {
        return dvbsupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.dvbsupport
     *
     * @param dvbsupport the value for advertisementmapping.dvbsupport
     *
     * @mbggenerated
     */
    public void setDvbsupport(Boolean dvbsupport) {
        this.dvbsupport = dvbsupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.homeui
     *
     * @return the value of advertisementmapping.homeui
     *
     * @mbggenerated
     */
    public String getHomeui() {
        return homeui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.homeui
     *
     * @param homeui the value for advertisementmapping.homeui
     *
     * @mbggenerated
     */
    public void setHomeui(String homeui) {
        this.homeui = homeui == null ? null : homeui.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.ipbegin
     *
     * @return the value of advertisementmapping.ipbegin
     *
     * @mbggenerated
     */
    public String getIpbegin() {
        return ipbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.ipbegin
     *
     * @param ipbegin the value for advertisementmapping.ipbegin
     *
     * @mbggenerated
     */
    public void setIpbegin(String ipbegin) {
        this.ipbegin = ipbegin == null ? null : ipbegin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisementmapping.ipend
     *
     * @return the value of advertisementmapping.ipend
     *
     * @mbggenerated
     */
    public String getIpend() {
        return ipend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisementmapping.ipend
     *
     * @param ipend the value for advertisementmapping.ipend
     *
     * @mbggenerated
     */
    public void setIpend(String ipend) {
        this.ipend = ipend == null ? null : ipend.trim();
    }

	public AdvertisementMapping(String romversion, String type, String userid,
			String appversion, String hardwareversion, String manufacturer, Boolean dvbsupport, String homeui,
			String ipbegin, String ipend) {
		super();
		this.romversion = romversion;
		this.type = type;
		this.userid = userid;
		this.appversion = appversion;
		this.hardwareversion = hardwareversion;
		this.manufacturer = manufacturer;
		this.dvbsupport = dvbsupport;
		this.homeui = homeui;
		this.ipbegin = ipbegin;
		this.ipend = ipend;
	}

	public AdvertisementMapping() {
		super();
	}
    
}