package com.ota.domain;

import java.util.Date;

public class Advertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.adversion
     *
     * @mbggenerated
     */
    private String adversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.download
     *
     * @mbggenerated
     */
    private String download;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.positionID
     *
     * @mbggenerated
     */
    private Integer positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.gotoUrl
     *
     * @mbggenerated
     */
    private String gotourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.mappingid
     *
     * @mbggenerated
     */
    private String mappingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.businessid
     *
     * @mbggenerated
     */
    private String businessid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.id
     *
     * @return the value of advertisement.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.id
     *
     * @param id the value for advertisement.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.adversion
     *
     * @return the value of advertisement.adversion
     *
     * @mbggenerated
     */
    public String getAdversion() {
        return adversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.adversion
     *
     * @param adversion the value for advertisement.adversion
     *
     * @mbggenerated
     */
    public void setAdversion(String adversion) {
        this.adversion = adversion == null ? null : adversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.update_time
     *
     * @return the value of advertisement.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.update_time
     *
     * @param updateTime the value for advertisement.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.download
     *
     * @return the value of advertisement.download
     *
     * @mbggenerated
     */
    public String getDownload() {
        return download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.download
     *
     * @param download the value for advertisement.download
     *
     * @mbggenerated
     */
    public void setDownload(String download) {
        this.download = download == null ? null : download.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.positionID
     *
     * @return the value of advertisement.positionID
     *
     * @mbggenerated
     */
    public Integer getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.positionID
     *
     * @param positionid the value for advertisement.positionID
     *
     * @mbggenerated
     */
    public void setPositionid(Integer positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.gotoUrl
     *
     * @return the value of advertisement.gotoUrl
     *
     * @mbggenerated
     */
    public String getGotourl() {
        return gotourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.gotoUrl
     *
     * @param gotourl the value for advertisement.gotoUrl
     *
     * @mbggenerated
     */
    public void setGotourl(String gotourl) {
        this.gotourl = gotourl == null ? null : gotourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.mappingid
     *
     * @return the value of advertisement.mappingid
     *
     * @mbggenerated
     */
    public String getMappingid() {
        return mappingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.mappingid
     *
     * @param mappingid the value for advertisement.mappingid
     *
     * @mbggenerated
     */
    public void setMappingid(String mappingid) {
        this.mappingid = mappingid == null ? null : mappingid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.businessid
     *
     * @return the value of advertisement.businessid
     *
     * @mbggenerated
     */
    public String getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.businessid
     *
     * @param businessid the value for advertisement.businessid
     *
     * @mbggenerated
     */
    public void setBusinessid(String businessid) {
        this.businessid = businessid == null ? null : businessid.trim();
    }

	public Advertisement(Integer id, String mappingid) {
		super();
		this.id = id;
		this.mappingid = mappingid;
	}

	public Advertisement() {
		super();
	}
    
    
}