package com.ota.domain;

public class AppLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.customer
     *
     * @mbggenerated
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.device
     *
     * @mbggenerated
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.appname
     *
     * @mbggenerated
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.packagename
     *
     * @mbggenerated
     */
    private String packagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.action
     *
     * @mbggenerated
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column applog.logtime
     *
     * @mbggenerated
     */
    private String logtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.id
     *
     * @return the value of applog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.id
     *
     * @param id the value for applog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.customer
     *
     * @return the value of applog.customer
     *
     * @mbggenerated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.customer
     *
     * @param customer the value for applog.customer
     *
     * @mbggenerated
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.model
     *
     * @return the value of applog.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.model
     *
     * @param model the value for applog.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.device
     *
     * @return the value of applog.device
     *
     * @mbggenerated
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.device
     *
     * @param device the value for applog.device
     *
     * @mbggenerated
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.appname
     *
     * @return the value of applog.appname
     *
     * @mbggenerated
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.appname
     *
     * @param appname the value for applog.appname
     *
     * @mbggenerated
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.packagename
     *
     * @return the value of applog.packagename
     *
     * @mbggenerated
     */
    public String getPackagename() {
        return packagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.packagename
     *
     * @param packagename the value for applog.packagename
     *
     * @mbggenerated
     */
    public void setPackagename(String packagename) {
        this.packagename = packagename == null ? null : packagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.version
     *
     * @return the value of applog.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.version
     *
     * @param version the value for applog.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.ip
     *
     * @return the value of applog.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.ip
     *
     * @param ip the value for applog.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.action
     *
     * @return the value of applog.action
     *
     * @mbggenerated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.action
     *
     * @param action the value for applog.action
     *
     * @mbggenerated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column applog.logtime
     *
     * @return the value of applog.logtime
     *
     * @mbggenerated
     */
    public String getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column applog.logtime
     *
     * @param logtime the value for applog.logtime
     *
     * @mbggenerated
     */
    public void setLogtime(String logtime) {
        this.logtime = logtime == null ? null : logtime.trim();
    }
}