package com.ota.domain;

public class AppstoreMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.romversion
     *
     * @mbggenerated
     */
    private String romversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.businessid
     *
     * @mbggenerated
     */
    private String businessid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.appversion
     *
     * @mbggenerated
     */
    private String appversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.hardwareversion
     *
     * @mbggenerated
     */
    private String hardwareversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.manufacturer
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.dvbsupport
     *
     * @mbggenerated
     */
    private Boolean dvbsupport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.homeui
     *
     * @mbggenerated
     */
    private String homeui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.ipbegin
     *
     * @mbggenerated
     */
    private String ipbegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appstoremapping.ipend
     *
     * @mbggenerated
     */
    private String ipend;

    

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.id
     *
     * @return the value of appstoremapping.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.id
     *
     * @param id the value for appstoremapping.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.romversion
     *
     * @return the value of appstoremapping.romversion
     *
     * @mbggenerated
     */
    public String getRomversion() {
        return romversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.romversion
     *
     * @param romversion the value for appstoremapping.romversion
     *
     * @mbggenerated
     */
    public void setRomversion(String romversion) {
        this.romversion = romversion == null ? null : romversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.type
     *
     * @return the value of appstoremapping.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.type
     *
     * @param type the value for appstoremapping.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.userid
     *
     * @return the value of appstoremapping.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.userid
     *
     * @param userid the value for appstoremapping.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.businessid
     *
     * @return the value of appstoremapping.businessid
     *
     * @mbggenerated
     */
    public String getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.businessid
     *
     * @param businessid the value for appstoremapping.businessid
     *
     * @mbggenerated
     */
    public void setBusinessid(String businessid) {
        this.businessid = businessid == null ? null : businessid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.appversion
     *
     * @return the value of appstoremapping.appversion
     *
     * @mbggenerated
     */
    public String getAppversion() {
        return appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.appversion
     *
     * @param appversion the value for appstoremapping.appversion
     *
     * @mbggenerated
     */
    public void setAppversion(String appversion) {
        this.appversion = appversion == null ? null : appversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.hardwareversion
     *
     * @return the value of appstoremapping.hardwareversion
     *
     * @mbggenerated
     */
    public String getHardwareversion() {
        return hardwareversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.hardwareversion
     *
     * @param hardwareversion the value for appstoremapping.hardwareversion
     *
     * @mbggenerated
     */
    public void setHardwareversion(String hardwareversion) {
        this.hardwareversion = hardwareversion == null ? null : hardwareversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.manufacturer
     *
     * @return the value of appstoremapping.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.manufacturer
     *
     * @param manufacturer the value for appstoremapping.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.dvbsupport
     *
     * @return the value of appstoremapping.dvbsupport
     *
     * @mbggenerated
     */
    public Boolean getDvbsupport() {
        return dvbsupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.dvbsupport
     *
     * @param dvbsupport the value for appstoremapping.dvbsupport
     *
     * @mbggenerated
     */
    public void setDvbsupport(Boolean dvbsupport) {
        this.dvbsupport = dvbsupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.homeui
     *
     * @return the value of appstoremapping.homeui
     *
     * @mbggenerated
     */
    public String getHomeui() {
        return homeui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.homeui
     *
     * @param homeui the value for appstoremapping.homeui
     *
     * @mbggenerated
     */
    public void setHomeui(String homeui) {
        this.homeui = homeui == null ? null : homeui.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.ipbegin
     *
     * @return the value of appstoremapping.ipbegin
     *
     * @mbggenerated
     */
    public String getIpbegin() {
        return ipbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.ipbegin
     *
     * @param ipbegin the value for appstoremapping.ipbegin
     *
     * @mbggenerated
     */
    public void setIpbegin(String ipbegin) {
        this.ipbegin = ipbegin == null ? null : ipbegin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appstoremapping.ipend
     *
     * @return the value of appstoremapping.ipend
     *
     * @mbggenerated
     */
    public String getIpend() {
        return ipend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appstoremapping.ipend
     *
     * @param ipend the value for appstoremapping.ipend
     *
     * @mbggenerated
     */
    public void setIpend(String ipend) {
        this.ipend = ipend == null ? null : ipend.trim();
    }
    
    
    
    public AppstoreMapping(String romVersion, String type, String userID, String appVersion,
			String hardwareversion, String manufacturer, Boolean dvbSupport, String homeUI, String ipbegin,
			String ipend) {
		super();
		this.romversion = romVersion;
		this.type = type;
		this.userid = userID;
		this.appversion = appVersion;
		this.hardwareversion = hardwareversion;
		this.manufacturer = manufacturer;
		this.dvbsupport = dvbSupport;
		this.homeui = homeUI;
		this.ipbegin = ipbegin;
		this.ipend = ipend;
    	
	}
    public AppstoreMapping() {
    	super();
    }
    
}