package com.ota.domain;

import java.util.Date;

public class BoxWithStatus {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.businessid
     *
     * @mbggenerated
     */
    private String businessid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.appversion
     *
     * @mbggenerated
     */
    private String appversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.romversion
     *
     * @mbggenerated
     */
    private String romversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.hardwareversion
     *
     * @mbggenerated
     */
    private String hardwareversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.manufacturer
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.dvbsupport
     *
     * @mbggenerated
     */
    private Boolean dvbsupport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.homeui
     *
     * @mbggenerated
     */
    private String homeui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.onlinetime
     *
     * @mbggenerated
     */
    private Date onlinetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column box.groupname
     *
     * @mbggenerated
     */
    private String groupname;
    
    private String customer;
    
    private String status;
    
    
    
    public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCustomer() {
		return customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.mac
     *
     * @return the value of box.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.mac
     *
     * @param mac the value for box.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.userid
     *
     * @return the value of box.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.userid
     *
     * @param userid the value for box.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.businessid
     *
     * @return the value of box.businessid
     *
     * @mbggenerated
     */
    public String getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.businessid
     *
     * @param businessid the value for box.businessid
     *
     * @mbggenerated
     */
    public void setBusinessid(String businessid) {
        this.businessid = businessid == null ? null : businessid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.type
     *
     * @return the value of box.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.type
     *
     * @param type the value for box.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.appversion
     *
     * @return the value of box.appversion
     *
     * @mbggenerated
     */
    public String getAppversion() {
        return appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.appversion
     *
     * @param appversion the value for box.appversion
     *
     * @mbggenerated
     */
    public void setAppversion(String appversion) {
        this.appversion = appversion == null ? null : appversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.romversion
     *
     * @return the value of box.romversion
     *
     * @mbggenerated
     */
    public String getRomversion() {
        return romversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.romversion
     *
     * @param romversion the value for box.romversion
     *
     * @mbggenerated
     */
    public void setRomversion(String romversion) {
        this.romversion = romversion == null ? null : romversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.hardwareversion
     *
     * @return the value of box.hardwareversion
     *
     * @mbggenerated
     */
    public String getHardwareversion() {
        return hardwareversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.hardwareversion
     *
     * @param hardwareversion the value for box.hardwareversion
     *
     * @mbggenerated
     */
    public void setHardwareversion(String hardwareversion) {
        this.hardwareversion = hardwareversion == null ? null : hardwareversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.manufacturer
     *
     * @return the value of box.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.manufacturer
     *
     * @param manufacturer the value for box.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.dvbsupport
     *
     * @return the value of box.dvbsupport
     *
     * @mbggenerated
     */
    public Boolean getDvbsupport() {
        return dvbsupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.dvbsupport
     *
     * @param dvbsupport the value for box.dvbsupport
     *
     * @mbggenerated
     */
    public void setDvbsupport(Boolean dvbsupport) {
        this.dvbsupport = dvbsupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.homeui
     *
     * @return the value of box.homeui
     *
     * @mbggenerated
     */
    public String getHomeui() {
        return homeui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.homeui
     *
     * @param homeui the value for box.homeui
     *
     * @mbggenerated
     */
    public void setHomeui(String homeui) {
        this.homeui = homeui == null ? null : homeui.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.onlinetime
     *
     * @return the value of box.onlinetime
     *
     * @mbggenerated
     */
    public Date getOnlinetime() {
        return onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.onlinetime
     *
     * @param onlinetime the value for box.onlinetime
     *
     * @mbggenerated
     */
    public void setOnlinetime(Date onlinetime) {
        this.onlinetime = onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column box.groupname
     *
     * @return the value of box.groupname
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column box.groupname
     *
     * @param groupname the value for box.groupname
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }
}
