package com.ota.domain;

public class BurnMacSN {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column burnmacsn.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column burnmacsn.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column burnmacsn.sn
     *
     * @mbggenerated
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column burnmacsn.newmac
     *
     * @mbggenerated
     */
    private String newmac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column burnmacsn.newsn
     *
     * @mbggenerated
     */
    private String newsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column burnmacsn.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column burnmacsn.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column burnmacsn.updatetime
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column burnmacsn.id
     *
     * @return the value of burnmacsn.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column burnmacsn.id
     *
     * @param id the value for burnmacsn.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column burnmacsn.mac
     *
     * @return the value of burnmacsn.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column burnmacsn.mac
     *
     * @param mac the value for burnmacsn.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column burnmacsn.sn
     *
     * @return the value of burnmacsn.sn
     *
     * @mbggenerated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column burnmacsn.sn
     *
     * @param sn the value for burnmacsn.sn
     *
     * @mbggenerated
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column burnmacsn.newmac
     *
     * @return the value of burnmacsn.newmac
     *
     * @mbggenerated
     */
    public String getNewmac() {
        return newmac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column burnmacsn.newmac
     *
     * @param newmac the value for burnmacsn.newmac
     *
     * @mbggenerated
     */
    public void setNewmac(String newmac) {
        this.newmac = newmac == null ? null : newmac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column burnmacsn.newsn
     *
     * @return the value of burnmacsn.newsn
     *
     * @mbggenerated
     */
    public String getNewsn() {
        return newsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column burnmacsn.newsn
     *
     * @param newsn the value for burnmacsn.newsn
     *
     * @mbggenerated
     */
    public void setNewsn(String newsn) {
        this.newsn = newsn == null ? null : newsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column burnmacsn.status
     *
     * @return the value of burnmacsn.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column burnmacsn.status
     *
     * @param status the value for burnmacsn.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column burnmacsn.createtime
     *
     * @return the value of burnmacsn.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column burnmacsn.createtime
     *
     * @param createtime the value for burnmacsn.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column burnmacsn.updatetime
     *
     * @return the value of burnmacsn.updatetime
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column burnmacsn.updatetime
     *
     * @param updatetime the value for burnmacsn.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }
}