package com.ota.domain;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.serverip
     *
     * @mbggenerated
     */
    private String serverip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.nation
     *
     * @mbggenerated
     */
    private String nation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.name
     *
     * @return the value of business.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.name
     *
     * @param name the value for business.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.serverip
     *
     * @return the value of business.serverip
     *
     * @mbggenerated
     */
    public String getServerip() {
        return serverip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.serverip
     *
     * @param serverip the value for business.serverip
     *
     * @mbggenerated
     */
    public void setServerip(String serverip) {
        this.serverip = serverip == null ? null : serverip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.nation
     *
     * @return the value of business.nation
     *
     * @mbggenerated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.nation
     *
     * @param nation the value for business.nation
     *
     * @mbggenerated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }
}