package com.ota.domain;

public class CustomerGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customergroup.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customergroup.groupid
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customergroup.customerid
     *
     * @mbggenerated
     */
    private Integer customerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customergroup.id
     *
     * @return the value of customergroup.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customergroup.id
     *
     * @param id the value for customergroup.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customergroup.groupid
     *
     * @return the value of customergroup.groupid
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customergroup.groupid
     *
     * @param groupid the value for customergroup.groupid
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customergroup.customerid
     *
     * @return the value of customergroup.customerid
     *
     * @mbggenerated
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customergroup.customerid
     *
     * @param customerid the value for customergroup.customerid
     *
     * @mbggenerated
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }
}