package com.ota.domain;

public class IPBlock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipblock.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipblock.ipbegin
     *
     * @mbggenerated
     */
    private String ipbegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipblock.ipend
     *
     * @mbggenerated
     */
    private String ipend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipblock.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ipblock.createtime
     *
     * @mbggenerated
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipblock.id
     *
     * @return the value of ipblock.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipblock.id
     *
     * @param id the value for ipblock.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipblock.ipbegin
     *
     * @return the value of ipblock.ipbegin
     *
     * @mbggenerated
     */
    public String getIpbegin() {
        return ipbegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipblock.ipbegin
     *
     * @param ipbegin the value for ipblock.ipbegin
     *
     * @mbggenerated
     */
    public void setIpbegin(String ipbegin) {
        this.ipbegin = ipbegin == null ? null : ipbegin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipblock.ipend
     *
     * @return the value of ipblock.ipend
     *
     * @mbggenerated
     */
    public String getIpend() {
        return ipend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipblock.ipend
     *
     * @param ipend the value for ipblock.ipend
     *
     * @mbggenerated
     */
    public void setIpend(String ipend) {
        this.ipend = ipend == null ? null : ipend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipblock.status
     *
     * @return the value of ipblock.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipblock.status
     *
     * @param status the value for ipblock.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ipblock.createtime
     *
     * @return the value of ipblock.createtime
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ipblock.createtime
     *
     * @param createtime the value for ipblock.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }
}