package com.ota.domain;

public class OTALog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otalog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otalog.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otalog.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otalog.currentVersion
     *
     * @mbggenerated
     */
    private String currentversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otalog.updateVersion
     *
     * @mbggenerated
     */
    private String updateversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otalog.ipaddress
     *
     * @mbggenerated
     */
    private String ipaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otalog.logtime
     *
     * @mbggenerated
     */
    private String logtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otalog.action
     *
     * @mbggenerated
     */
    private String action;
    private String customer;
    

    public String getCustomer() {
		return customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otalog.id
     *
     * @return the value of otalog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otalog.id
     *
     * @param id the value for otalog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otalog.mac
     *
     * @return the value of otalog.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otalog.mac
     *
     * @param mac the value for otalog.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otalog.model
     *
     * @return the value of otalog.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otalog.model
     *
     * @param model the value for otalog.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otalog.currentVersion
     *
     * @return the value of otalog.currentVersion
     *
     * @mbggenerated
     */
    public String getCurrentversion() {
        return currentversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otalog.currentVersion
     *
     * @param currentversion the value for otalog.currentVersion
     *
     * @mbggenerated
     */
    public void setCurrentversion(String currentversion) {
        this.currentversion = currentversion == null ? null : currentversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otalog.updateVersion
     *
     * @return the value of otalog.updateVersion
     *
     * @mbggenerated
     */
    public String getUpdateversion() {
        return updateversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otalog.updateVersion
     *
     * @param updateversion the value for otalog.updateVersion
     *
     * @mbggenerated
     */
    public void setUpdateversion(String updateversion) {
        this.updateversion = updateversion == null ? null : updateversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otalog.ipaddress
     *
     * @return the value of otalog.ipaddress
     *
     * @mbggenerated
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otalog.ipaddress
     *
     * @param ipaddress the value for otalog.ipaddress
     *
     * @mbggenerated
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress == null ? null : ipaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otalog.logtime
     *
     * @return the value of otalog.logtime
     *
     * @mbggenerated
     */
    public String getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otalog.logtime
     *
     * @param logtime the value for otalog.logtime
     *
     * @mbggenerated
     */
    public void setLogtime(String logtime) {
        this.logtime = logtime == null ? null : logtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otalog.action
     *
     * @return the value of otalog.action
     *
     * @mbggenerated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otalog.action
     *
     * @param action the value for otalog.action
     *
     * @mbggenerated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

	@Override
	public String toString() {
		return "OTALog [id=" + id + ", mac=" + mac + ", model=" + model + ", currentversion=" + currentversion
				+ ", updateversion=" + updateversion + ", ipaddress=" + ipaddress + ", logtime=" + logtime + ", action="
				+ action + "]";
	}
    
}