package com.ota.domain;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.authority1
     *
     * @mbggenerated
     */
    private String authority1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.authority2
     *
     * @mbggenerated
     */
    private String authority2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.authority3
     *
     * @mbggenerated
     */
    private String authority3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role
     *
     * @return the value of t_role.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role
     *
     * @param role the value for t_role.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.authority1
     *
     * @return the value of t_role.authority1
     *
     * @mbggenerated
     */
    public String getAuthority1() {
        return authority1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.authority1
     *
     * @param authority1 the value for t_role.authority1
     *
     * @mbggenerated
     */
    public void setAuthority1(String authority1) {
        this.authority1 = authority1 == null ? null : authority1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.authority2
     *
     * @return the value of t_role.authority2
     *
     * @mbggenerated
     */
    public String getAuthority2() {
        return authority2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.authority2
     *
     * @param authority2 the value for t_role.authority2
     *
     * @mbggenerated
     */
    public void setAuthority2(String authority2) {
        this.authority2 = authority2 == null ? null : authority2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.authority3
     *
     * @return the value of t_role.authority3
     *
     * @mbggenerated
     */
    public String getAuthority3() {
        return authority3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.authority3
     *
     * @param authority3 the value for t_role.authority3
     *
     * @mbggenerated
     */
    public void setAuthority3(String authority3) {
        this.authority3 = authority3 == null ? null : authority3.trim();
    }
}