package com.ota.domain;

import java.util.Date;

public class Updatefile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updatefile.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updatefile.file_version
     *
     * @mbggenerated
     */
    private String fileVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updatefile.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updatefile.download
     *
     * @mbggenerated
     */
    private String download;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updatefile.md5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updatefile.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updatefile.mappingid
     *
     * @mbggenerated
     */
    private String mappingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updatefile.businessid
     *
     * @mbggenerated
     */
    private String description;
    
    private String businessid;
    private Integer groupid;
    private Integer modelid;
    
    private String enforce;
    private String status;



	public String getBusinessid() {
		return businessid;
	}

	public void setBusinessid(String businessid) {
		this.businessid = businessid;
	}

	public Integer getGroupid() {
		return groupid;
	}

	public void setGroupid(Integer groupid) {
		this.groupid = groupid;
	}

	public Integer getModelid() {
		return modelid;
	}

	public void setModelid(Integer modelid) {
		this.modelid = modelid;
	}

	public String getEnforce() {
		return enforce;
	}

	public void setEnforce(String enforce) {
		this.enforce = enforce;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column updatefile.id
     *
     * @return the value of updatefile.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column updatefile.id
     *
     * @param id the value for updatefile.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column updatefile.file_version
     *
     * @return the value of updatefile.file_version
     *
     * @mbggenerated
     */
    public String getFileVersion() {
        return fileVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column updatefile.file_version
     *
     * @param fileVersion the value for updatefile.file_version
     *
     * @mbggenerated
     */
    public void setFileVersion(String fileVersion) {
        this.fileVersion = fileVersion == null ? null : fileVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column updatefile.update_time
     *
     * @return the value of updatefile.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column updatefile.update_time
     *
     * @param updateTime the value for updatefile.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column updatefile.download
     *
     * @return the value of updatefile.download
     *
     * @mbggenerated
     */
    public String getDownload() {
        return download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column updatefile.download
     *
     * @param download the value for updatefile.download
     *
     * @mbggenerated
     */
    public void setDownload(String download) {
        this.download = download == null ? null : download.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column updatefile.md5
     *
     * @return the value of updatefile.md5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column updatefile.md5
     *
     * @param md5 the value for updatefile.md5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column updatefile.size
     *
     * @return the value of updatefile.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column updatefile.size
     *
     * @param size the value for updatefile.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column updatefile.mappingid
     *
     * @return the value of updatefile.mappingid
     *
     * @mbggenerated
     */
    public String getMappingid() {
        return mappingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column updatefile.mappingid
     *
     * @param mappingid the value for updatefile.mappingid
     *
     * @mbggenerated
     */
    public void setMappingid(String mappingid) {
        this.mappingid = mappingid == null ? null : mappingid.trim();
    }

    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column updatefile.description
     *
     * @param description the value for updatefile.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }


	public Updatefile(Integer id, String mappingid) {
		super();
		this.id = id;
		this.mappingid = mappingid;
	}

	public Updatefile() {
		super();
	}

	@Override
	public String toString() {
		return "Updatefile [id=" + id + ", fileVersion=" + fileVersion + ", updateTime=" + updateTime + ", download="
				+ download + ", md5=" + md5 + ", size=" + size + ", mappingid=" + mappingid + ", description="
				+ description + ", businessid=" + businessid + ", groupid=" + groupid + ", modelid=" + modelid
				+ ", enforce=" + enforce + ", status=" + status + "]";
	}
	
	
    
    
}