package com.ota.dao;

import java.util.List;
import java.util.Map;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ota.domain.AdverInfo;
import com.ota.domain.Advertisement;
import com.ota.domain.AdvertisementInfo;

public interface AdvertisementMapper {
	
	List<AdvertisementInfo> selectAdvertisementInfo(AdvertisementInfo advertisementInfo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    int insert(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    int insertSelective(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    Advertisement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Advertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Advertisement record);

	String[] selectByAdversion(String adversion);
	List<Advertisement> selectByBusinessId(String businessid);
	List<Advertisement> selectForRoot();
	void updateMappingIDByPrimaryKey(Advertisement advertisement);
	int selectlastid();
	void updateForAddFilterToMultFile(Advertisement advertisement);
	List<AdverInfo> selectAllAdvertisementWithFilter(
			Map<String, Object> map, PageBounds pageBounds);
}