package com.ota.dao;

import java.util.List;
import java.util.Map;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ota.domain.AppLog;
import com.ota.domain.OTALog;

public interface AppLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog
     *
     * @mbggenerated
     */
    int insert(AppLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog
     *
     * @mbggenerated
     */
    int insertSelective(AppLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog
     *
     * @mbggenerated
     */
    AppLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppLog record);

	List<OTALog> selectAppLogsWithFilter(Map<String, Object> map, PageBounds pageBounds);

	int countAppLogsWithFilter(Map<String, Object> map);
}