package com.ota.dao;

import java.util.List;
import java.util.Map;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ota.domain.Appstore;
import com.ota.domain.AppstoreInfo;
import com.ota.domain.AppstoreWithAllInfo;

public interface AppstoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appstore
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appstore
     *
     * @mbggenerated
     */
    int insert(Appstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appstore
     *
     * @mbggenerated
     */
    int insertSelective(Appstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appstore
     *
     * @mbggenerated
     */
    Appstore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appstore
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Appstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appstore
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Appstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appstore
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Appstore record);

	List<Appstore> selectForRoot();

	List<Appstore> selectByBusinessId(String businessid);

	void updateMappingIDByPrimaryKey(Appstore appstore);

	int selectlastid();

	List<AppstoreInfo> selectAppstoreInfo(AppstoreInfo appstoreInfo);

	void updateForAddFilterToMultFile(Appstore appstore);

	List<AppstoreWithAllInfo> selectAllAppstoreInfoWithFilter(Map<String, Object> map, PageBounds pageBounds);
}