package com.ota.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ota.domain.Box;

public interface BoxMapper {
	
	int statistic();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbggenerated
     */
    int insert(Box record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbggenerated
     */
    int insertSelective(Box record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbggenerated
     */
    Box selectByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Box record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table box
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Box record);
    int updateByPrimaryKeySelectiveWithoutTime(Box box);
    
	List<Box> selectOnlineBox(String businessid);
	List<Box> selectBox();
	List<Box> selectOfflineBox(String businessid);
	List<Box> selectOnlineBoxWithFilter(Map<String, Object> map, PageBounds pageBounds);
	List<Box> selectOfflineBoxWithFilter(Map<String, Object> map, PageBounds pageBounds);
	int countOfflineWithFilter(Map<String, Object> map);
	int countOnlineWithFilter(Map<String, Object> map);
	void updateOnlineTime(Box box);
	void deleteByCustomerIdAndGroupId(HashMap<String, Integer> map);
}