package com.ota.dao;

import java.util.List;
import java.util.Map;

import com.ota.domain.BoxType;

public interface BoxTypeMapper {
	
	List<BoxType> selectAllType();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boxtype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boxtype
     *
     * @mbggenerated
     */
    int insert(BoxType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boxtype
     *
     * @mbggenerated
     */
    int insertSelective(BoxType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boxtype
     *
     * @mbggenerated
     */
    BoxType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boxtype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BoxType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boxtype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BoxType record);
	int checkNewProduct(Map<String, String> map);
	int selectModelIDByType(String model);
}