package com.ota.dao;

import java.util.List;
import java.util.Map;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ota.domain.BurnMacSN;

public interface BurnMacSNMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table burnmacsn
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table burnmacsn
     *
     * @mbggenerated
     */
    int insert(BurnMacSN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table burnmacsn
     *
     * @mbggenerated
     */
    int insertSelective(BurnMacSN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table burnmacsn
     *
     * @mbggenerated
     */
    BurnMacSN selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table burnmacsn
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BurnMacSN record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table burnmacsn
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BurnMacSN record);

	List<BurnMacSN> selectAllWithFilter(Map<String, Object> map, PageBounds pageBounds);

	int countAllWithFilter(Map<String, Object> map, PageBounds pageBounds);
}