package com.ota.dao;

import java.util.List;
import java.util.Map;

import com.ota.domain.CustomerGroup;
import com.ota.domain.CustomerGroupDetail;

public interface CustomerGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customergroup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customergroup
     *
     * @mbggenerated
     */
    int insert(CustomerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customergroup
     *
     * @mbggenerated
     */
    int insertSelective(CustomerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customergroup
     *
     * @mbggenerated
     */
    CustomerGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customergroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customergroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerGroup record);

	List<Integer> selectGroupIDByCustomerID(int businessid);

	List<CustomerGroupDetail> selectAllCustomerNameAndGroupName();

	int checkNewGroup(Map<String, Integer> map);

	int countGroup(int customerid);
}