package com.ota.dao;

import java.util.List;

import com.ota.domain.Box;
import com.ota.domain.FileMapping;

public interface FileMappingMapper {
	int insertAndGetId(FileMapping fileMapping);
	int selectlastid();
	List<FileMapping> selectByTypeAndRomVersion(Box box);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filemapping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filemapping
     *
     * @mbggenerated
     */
    int insert(FileMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filemapping
     *
     * @mbggenerated
     */
    int insertSelective(FileMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filemapping
     *
     * @mbggenerated
     */
    FileMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filemapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filemapping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileMapping record);
}