package com.ota.dao;

import java.util.List;

import com.ota.domain.OTAGroup;

public interface OTAGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otagroup
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otagroup
     *
     * @mbggenerated
     */
    int insert(OTAGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otagroup
     *
     * @mbggenerated
     */
    int insertSelective(OTAGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otagroup
     *
     * @mbggenerated
     */
    OTAGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otagroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OTAGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otagroup
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OTAGroup record);

	String selectGroupnameByPrimaryKey(int id);

	List<String> selectAllGroupname();

	Integer selectGroupIDByGroupName(String group);

	int checkhasGroupname(String groupname);

	int selectMaxGroupSort();

	Integer selectSortByGroupid(int i);
}