package com.ota.dao;

import java.util.List;
import java.util.Map;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ota.domain.OTALog;

public interface OTALogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otalog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otalog
     *
     * @mbggenerated
     */
    int insert(OTALog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otalog
     *
     * @mbggenerated
     */
    int insertSelective(OTALog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otalog
     *
     * @mbggenerated
     */
    OTALog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otalog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OTALog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otalog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OTALog record);
    
    List<OTALog> selectAllOTALog();

	List<OTALog> selectOTALogsWithFilter(Map<String, Object> map, PageBounds pageBounds);

	int countOTALogsWithFilter(Map<String, Object> map);
}