package com.ota.dao;

import java.util.List;
import java.util.Map;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.ota.domain.FileMapping;
import com.ota.domain.UpdateFileInfo;
import com.ota.domain.Updatefile;

public interface UpdatefileMapper {
	List<Updatefile> selectByBusinessId(String BusinessID);
	List<Updatefile> selectForRoot();
	void deleteMappingID(FileMapping filemapping);

	int selectlastid();

	Updatefile selectByMappingid(FileMapping fm);

	int insertAndGetId(Updatefile updatefile);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table updatefile
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table updatefile
	 *
	 * @mbggenerated
	 */
	int insert(Updatefile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table updatefile
	 *
	 * @mbggenerated
	 */
	int insertSelective(Updatefile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table updatefile
	 *
	 * @mbggenerated
	 */
	Updatefile selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table updatefile
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Updatefile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table updatefile
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Updatefile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table updatefile
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Updatefile record);
	List<UpdateFileInfo> selectAllUpdateFile();
	List<UpdateFileInfo> selectAllUpdateFileWithFilter(Map<String, Object> map, PageBounds pageBounds);
}